project_name: devopsctl
version: 2

release:
  prerelease: auto
  draft: true
  name_template: "DevOps CTL {{.Version}}"

builds:
  - id: macOS #build:macOS
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]
    binary: bin/devopsctl
    main: ./cmd/devopsctl
    ldflags:
      - -s -w

  - id: linux #build:linux
    goos: [ linux ]
    goarch: [ arm, amd64, arm64 ]
    env:
      - CGO_ENABLED=0
    binary: bin/devopsctl
    main: ./cmd/devopsctl
    ldflags:
      - -s -w

  - id: windows #build:windows
    goos: [ windows ]
    goarch: [ amd64, arm64 ]
    binary: bin/devopsctl
    main: ./cmd/devopsctl
    ldflags:
      - -s -w

archives:
  - id: linux-archive
    ids: [ linux ]
    name_template: "devopsctl_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    formats: [ 'tar.gz' ]
  - id: macOS-archive
    ids: [ macOS ]
    name_template: "devopsctl_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    formats: [ 'zip' ]
  - id: windows-archive
    ids: [ windows ]
    name_template: "devopsctl_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    formats: [ 'zip' ]
