project_name: devctl
version: 2

release:
  prerelease: auto
  draft: true
  name_template: "DEV CTL {{.Version}}"

before:
  hooks:
    - >- # The linux and windows archives package the manpages below
      {{ if eq .Runtime.Goos "windows" }}echo{{ end }} make manpages GH_VERSION={{.Version}}
    - >- # On linux the completions are used in nfpms below, but on macos they are used outside in the deployment build.
      {{ if eq .Runtime.Goos "windows" }}echo{{ end }} make completions
    - >- # We need to create the `.syso` files (per architecture) to embed Windows resources (version info)
      {{ if ne .Runtime.Goos "windows" }}echo{{ end }} pwsh '.\scripts\gen-winres.ps1' '{{ .Version }} ({{time "2006-01-02"}})' '{{ .Version }}' '.\scripts\versioninfo.template.json' '.\cmd\devctl\'

builds:
  - id: macos #build:macos
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]
    binary: bin/devctl
    main: ./cmd/devctl
    ldflags:
      - -s -w

  - id: linux #build:linux
    goos: [ linux ]
    goarch: [ arm, amd64, arm64 ]
    env:
      - CGO_ENABLED=0
    binary: bin/devctl
    main: ./cmd/devctl
    ldflags:
      - -s -w

  - id: windows #build:windows
    goos: [ windows ]
    goarch: [ amd64, arm64 ]
    binary: bin/devctl
    main: ./cmd/devctl
    ldflags:
      - -s -w

archives:
  - id: linux-archive
    ids: [ linux ]
    name_template: "devctl_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    formats: [ 'tar.gz' ]
  - id: macos-archive
    ids: [ macos ]
    name_template: "devctl_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    formats: [ 'zip' ]
  - id: windows-archive
    ids: [ windows ]
    name_template: "devctl_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    formats: [ 'zip' ]
