#!/bin/bash
set -e

if [ $# -eq 0 ]; then
  echo "usage: script/label-assets dist/devctl_*" >&2
  exit 1
fi

for asset; do
  label="$(basename "$asset")"
  label="DevCTL-$(tr '_' '-' <<<"${label#devctl_}")"
  printf '"%s#%s"\n' "$asset" "$label"
done